[package]
name = "kernel"
version = "0.0.0"
authors = ["Hailey Somerville <hailey@hailey.lol>"]
edition = "2018"

[dependencies]
core = { package = "core-futures-tls", version = "0.1" }
alloc_collections = { path = "../alloc_collections" }
bitflags = "1.0"
static_assertions = "0.3"
x86_64 = "0.7"
interface = { path = "../interface" }
kernel_derive = { path = "../kernel_derive" }
