[package]
name = "kernel"
version = "0.0.0"
authors = ["Hailey Somerville <hailey@hailey.lol>"]
edition = "2018"

[dependencies]
bitflags = "1.0"
x86 = "0.15"
gimli = { version = "0.18.0", default-features = false, features = ["read", "alloc"] }
fallible-iterator = { version = "0.2.0", default-features = false, features = ["alloc"] }
